=== mohit-bohra-dev/LoanOps-Agent/data/schemas/loan_api/payment-schedule.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "payment-schedule.schema.json",
  "title": "LoanServices PaymentSchedules response",
  "type": "array",
  "minItems": 1,
  "items": {
    "type": "object",
    "required": [
      "PaymentScheduleId",
      "LoanId",
      "NextPaymentDueDate",
      "PaymentDueMonth",
      "TotalPaymentAmount",
      "PendingEscrowPaymentAmount",
      "MonthlyPaymentPrincipalAmount",
      "MonthlyPaymentInterestAmount"
    ],
    "properties": {
      "PaymentScheduleId": { "type": "integer" },
      "LoanId": { "type": "integer" },
      "NextPaymentDueDate": { "type": "string", "format": "date-time" },
      "PaymentDueMonth": { "type": "string", "format": "date-time" },
      "TotalPaymentAmount": { "type": "number" },
      "PendingEscrowPaymentAmount": { "type": "number" },
      "InterestRate": { "type": "number" },
      "MonthlyPaymentAmount": { "type": "number" },
      "MonthlyPaymentPrincipalAmount": { "type": "number" },
      "MonthlyPaymentInterestAmount": { "type": "number" },
      "MonthlyCountyTaxAmount": { "type": "number" },
      "MonthlyHazardInsuranceAmount": { "type": "number" },
      "QuotedLateChargeFeeAmount": { "type": "number" },
      "LateChargeGraceEndDate": { "type": ["string", "null"], "format": "date-time" }
    },
    "additionalProperties": true
  }
}

=== mohit-bohra-dev/LoanOps-Agent/data/fixtures/loan_api/100721/payment_schedules.json
[
  {
    "PaymentScheduleId": 1007210,
    "LoanId": 100721,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-06-01T00:00:00",
    "TotalPaymentAmount": 1250.25,
    "PendingEscrowPaymentAmount": 360,
    "InterestRate": 0.051,
    "MonthlyPaymentAmount": 890.25,
    "MonthlyPaymentPrincipalAmount": 311.59,
    "MonthlyPaymentInterestAmount": 578.66,
    "MonthlyCountyTaxAmount": 216,
    "MonthlyHazardInsuranceAmount": 144,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-06-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1007211,
    "LoanId": 100721,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-07-01T00:00:00",
    "TotalPaymentAmount": 1250.25,
    "PendingEscrowPaymentAmount": 360,
    "InterestRate": 0.051,
    "MonthlyPaymentAmount": 890.25,
    "MonthlyPaymentPrincipalAmount": 311.59,
    "MonthlyPaymentInterestAmount": 578.66,
    "MonthlyCountyTaxAmount": 216,
    "MonthlyHazardInsuranceAmount": 144,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-07-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1007212,
    "LoanId": 100721,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-08-01T00:00:00",
    "TotalPaymentAmount": 1250.25,
    "PendingEscrowPaymentAmount": 360,
    "InterestRate": 0.051,
    "MonthlyPaymentAmount": 890.25,
    "MonthlyPaymentPrincipalAmount": 311.59,
    "MonthlyPaymentInterestAmount": 578.66,
    "MonthlyCountyTaxAmount": 216,
    "MonthlyHazardInsuranceAmount": 144,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-08-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1007213,
    "LoanId": 100721,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-09-01T00:00:00",
    "TotalPaymentAmount": 1250.25,
    "PendingEscrowPaymentAmount": 360,
    "InterestRate": 0.051,
    "MonthlyPaymentAmount": 890.25,
    "MonthlyPaymentPrincipalAmount": 311.59,
    "MonthlyPaymentInterestAmount": 578.66,
    "MonthlyCountyTaxAmount": 216,
    "MonthlyHazardInsuranceAmount": 144,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-09-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1007214,
    "LoanId": 100721,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-10-01T00:00:00",
    "TotalPaymentAmount": 1250.25,
    "PendingEscrowPaymentAmount": 360,
    "InterestRate": 0.051,
    "MonthlyPaymentAmount": 890.25,
    "MonthlyPaymentPrincipalAmount": 311.59,
    "MonthlyPaymentInterestAmount": 578.66,
    "MonthlyCountyTaxAmount": 216,
    "MonthlyHazardInsuranceAmount": 144,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-10-01T00:00:00"
  }
]

=== mohit-bohra-dev/LoanOps-Agent/projects/LoanOps.Common/packages/common/providers/tests/fixtures/loan_api/100245/payment_schedules.json
[
  {
    "PaymentScheduleId": 1002450,
    "LoanId": 100245,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-06-01T00:00:00",
    "TotalPaymentAmount": 2207.97,
    "PendingEscrowPaymentAmount": 615.3,
    "InterestRate": 0.04375,
    "MonthlyPaymentAmount": 1592.67,
    "MonthlyPaymentPrincipalAmount": 557.43,
    "MonthlyPaymentInterestAmount": 1035.24,
    "MonthlyCountyTaxAmount": 369.18,
    "MonthlyHazardInsuranceAmount": 246.12,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-06-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1002451,
    "LoanId": 100245,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-07-01T00:00:00",
    "TotalPaymentAmount": 2207.97,
    "PendingEscrowPaymentAmount": 615.3,
    "InterestRate": 0.04375,
    "MonthlyPaymentAmount": 1592.67,
    "MonthlyPaymentPrincipalAmount": 557.43,
    "MonthlyPaymentInterestAmount": 1035.24,
    "MonthlyCountyTaxAmount": 369.18,
    "MonthlyHazardInsuranceAmount": 246.12,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-07-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1002452,
    "LoanId": 100245,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-08-01T00:00:00",
    "TotalPaymentAmount": 2207.97,
    "PendingEscrowPaymentAmount": 615.3,
    "InterestRate": 0.04375,
    "MonthlyPaymentAmount": 1592.67,
    "MonthlyPaymentPrincipalAmount": 557.43,
    "MonthlyPaymentInterestAmount": 1035.24,
    "MonthlyCountyTaxAmount": 369.18,
    "MonthlyHazardInsuranceAmount": 246.12,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-08-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1002453,
    "LoanId": 100245,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-09-01T00:00:00",
    "TotalPaymentAmount": 2207.97,
    "PendingEscrowPaymentAmount": 615.3,
    "InterestRate": 0.04375,
    "MonthlyPaymentAmount": 1592.67,
    "MonthlyPaymentPrincipalAmount": 557.43,
    "MonthlyPaymentInterestAmount": 1035.24,
    "MonthlyCountyTaxAmount": 369.18,
    "MonthlyHazardInsuranceAmount": 246.12,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-09-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1002454,
    "LoanId": 100245,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-10-01T00:00:00",
    "TotalPaymentAmount": 2207.97,
    "PendingEscrowPaymentAmount": 615.3,
    "InterestRate": 0.04375,
    "MonthlyPaymentAmount": 1592.67,
    "MonthlyPaymentPrincipalAmount": 557.43,
    "MonthlyPaymentInterestAmount": 1035.24,
    "MonthlyCountyTaxAmount": 369.18,
    "MonthlyHazardInsuranceAmount": 246.12,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-10-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1002455,
    "LoanId": 100245,
    "NextPaymentDueDate": "2026-06-01T00:00:00",
    "PaymentDueMonth": "2026-11-01T00:00:00",
    "TotalPaymentAmount": 2207.97,
    "PendingEscrowPaymentAmount": 615.3,
    "InterestRate": 0.04375,
    "MonthlyPaymentAmount": 1592.67,
    "MonthlyPaymentPrincipalAmount": 557.43,
    "MonthlyPaymentInterestAmount": 1035.24,
    "MonthlyCountyTaxAmount": 369.18,
    "MonthlyHazardInsuranceAmount": 246.12,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2026-11-01T00:00:00"
  }
]

=== mohit-bohra-dev/LoanOps-Agent/data/fixtures/loan_api/100910/payment_schedules.json
[
  {
    "PaymentScheduleId": 1009100,
    "LoanId": 100910,
    "NextPaymentDueDate": "2024-12-01T00:00:00",
    "PaymentDueMonth": "2024-12-01T00:00:00",
    "TotalPaymentAmount": 0,
    "PendingEscrowPaymentAmount": 0,
    "InterestRate": 0.0375,
    "MonthlyPaymentAmount": 0,
    "MonthlyPaymentPrincipalAmount": 0,
    "MonthlyPaymentInterestAmount": 0,
    "MonthlyCountyTaxAmount": 0,
    "MonthlyHazardInsuranceAmount": 0,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2024-12-01T00:00:00"
  },
  {
    "PaymentScheduleId": 1009101,
    "LoanId": 100910,
    "NextPaymentDueDate": "2024-12-01T00:00:00",
    "PaymentDueMonth": "2025-01-01T00:00:00",
    "TotalPaymentAmount": 0,
    "PendingEscrowPaymentAmount": 0,
    "InterestRate": 0.0375,
    "MonthlyPaymentAmount": 0,
    "MonthlyPaymentPrincipalAmount": 0,
    "MonthlyPaymentInterestAmount": 0,
    "MonthlyCountyTaxAmount": 0,
    "MonthlyHazardInsuranceAmount": 0,
    "QuotedLateChargeFeeAmount": 35,
    "LateChargeGraceEndDate": "2025-01-01T00:00:00"
  }
]
